name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux
    strategy:
      matrix:
        toolchain: [stable]

    steps:
    - uses: actions/checkout@v4

    - name: Install linux deps
      run: |
        # pacman-contrib is for updpkgsums
        pacman -Syu git base-devel sudo just namcap pacman-contrib --noconfirm --needed
      
    - name: Test this ver
      run: just test-this-ver
