name: Scheduled tests

on:
  schedule:
    # Once a week at 5:30 on a saturday
    - cron: '30 5 * * 6'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux
    strategy:
      matrix:
        toolchain: [stable]

    steps:
    - uses: actions/checkout@v4

    - name: Install linux deps
      run: |
        # pacman-contrib is for updpkgsums
        pacman -Syu git base-devel sudo just namcap pacman-contrib rust --noconfirm --needed

    - name: Check upstream ver
      continue-on-error: true
      run: just check-upstream-ver
      
    - name: Test this ver
      continue-on-error: true
      # NOTE: makepkg can't run as root so this is the workaround
      run: |
        sudo chown -R nobody:nobody .
        sudo -u nobody just test-this-ver
      
    - name: Test upstream ver
      run: just update-to-upstream
      
